sentence_dict = {
    'M: Excuse me, the micle is in the right way for a few far?': 'M: Excuse me, is this the right way to "hill farm"?',
    "Walk him to I fill Farm.": 'Walk him to "Hill Farm".',
    "In an of fice.": "In an office.",
     "M: It was an exc iting football match. France against Germany. When the France were about to win... "
     "So, I got up late and didn't have breakfast and left home in a hurry.":  "M: It was an exciting football match. "
                                                                               "France against Germany. When the "
                                                                               "French were about to win... "
                                                                               "So, I got up late and didn't have "
                                                                               "breakfast and left home in a hurry.",
    "Man: Well, you know, it ... it kind of irks me it when hotels nickel-and-dime their customers like this. "
    "I mean, I checked with sev(eral hotels) ... I mean I checked with sev(eral hotels) ...": " Man: Well, you know, "
                                                                                              "it ... it kind of irks "
                                                                                              "me it when hotels "
                                                                                              "nickel-and-dime their "
                                                                                              "customers like this. "
                                                                                              "I mean, I checked with "
                                                                                              "several hotels ... I "
                                                                                              "mean I checked with "
                                                                                              "several hotels ...",
    "Where does this conve rsation take place?": "'Where does this conversation take place?",
    "W: Well, to tell the truth I don't car emuch dessert.": " W: Well, to tell the truth I don't care much for "
                                                             "dessert.",
    "W: I forget to tell you that the couple Simth won't come.": "W: I forget to tell you that the Smith couple "
                                                              "won't be coming.",
    "Where does the dialogue most probab ly take place?": "Where does the dialogue most probably take place?",
    'Why is the science exam diff icult?': 'Why is the science exam difficult?',
    'What is the propable relationship between the speakers?': 'What is the relationship between the speakers?'

}

spacing_dict = {
    'tothe': 'to the',
    'mayfail': 'may fail',
    'kungfu': 'kung fu',
    'thesame': 'the same',
    'whdavis': 'w . h . davis',
    'gatenine': 'gate nine',
    'youlend': 'you lend',
    "parisin": "paris in",
    'inever': 'i never',
    'hotdogs': 'hot dogs',
    'bymistake': 'by mistake',
    "konghotel": "kong hotel",
    'istill': 'i still',
    'begood': 'be good',
    'mynew': 'my new',
    'libtary': 'library',
    'suitcasefor': 'suitcase for',
    'inthe': 'in the',
    'twomonths': 'two months',
    'managerhere': 'manager here',
    'yourown': 'your own',
    'myown': 'my own',
    'isslower': 'is slower',
    'nextsemester': 'next semester',
    'couldyou': 'could you',
    'betterroads': 'better roads',
    'thelevel': 'the level',
    'theregion': 'the region',
    'ahistory': 'a history',
    'spendthe': 'spend the',
    'whyis': 'why is',
    'hishomework': 'his homework',
    'firstjob': 'first job',
    'twobedroom': 'two bedroom',
    'thestop': 'the stop',
    'ofschool': 'of school',
    'ticketsfor': 'tickets for',
    'dragonprogram': 'dragon program',
    'greensguest': 'greens guest',
    'baskguest': 'bask guest',
    'aminute': 'a minute',
    'somenews': 'some news',
    'werein': 'were in',
    'muchclothes': 'much clothes',
    'gotfor': 'got for',
    'untilthursday': 'until thursday',
    'thecharges': 'the charges',
    'rightafter': 'right after',
    'tomove': 'to move',
    'comfortableand': 'comfortable and',
    'dinnertonight': 'dinner tonight',
    'highschool': 'high school',
    'neverregretted': 'never regretted',
    'andtry': 'and try',
    'sorryto': 'sorry to',
    'ofmodern': 'of modern',
    'tobuy': 'to buy',
    'intown': 'in town',
    'collegenext': 'college next',
    'theirschool': 'their school',
    'tostay': 'to stay',
    'haha': 'ha ha',
    'verydull': 'very dull',
    'toknow': 'to know',
    "hongkong": "hong kong",
    "kingsize": "king size",
    "samecover": "same cover",
    "n't": ' not',
    "tvsets": "tv sets",
    "wednesdaymeeting": 'wednesday meeting',
    "abouthis": 'about his',
    "withthe": 'with the',
    "forit": 'for it',
    "tocome": 'to come',
    "nobath": 'no bath',
    "stationinformation": 'station information',
    "fiftypercent": 'fifty percent',
    "hearthat": 'hear that',
    "newjob": 'new job',
    "sohot": 'so hot',
    "theshelf": 'the shelf',
    "yorkas": "york as",
    "meetagain": 'meet again',
    "offto": 'off to',
    "worldclassics": "world classics",
    "meduring": "me during",
    "tosketch": 'to sketch',
    "gothere": 'go there',
    "supersocial": 'super social',
    "youdecideon": 'you decide on',
    "bestwriters": "best writers",
    "inspiredby": 'inspired by',
    "dothink": 'do think',
    "matterwhich": 'matter which',
    "yousmoke": 'you smoke',
    "booksection": 'book section',
    "fromthe": 'from the',
    "wellas": 'well as',
    " ican": ' i can',
    "thankyou": 'thank you',
    "haveto": 'have to',
    "homein": 'home in',
    "atweekends": 'on weekends',
    "midtermexam": 'midterm exam',
    '.': ' . ',
    '?': ' ? ',
    '!': ' ! ',
    '~': ' ~ ',
    '×': ' × ',
    '%': ' % ',
    '°': ' ° ',
    '$': ' $ ',
    '£': ' £ ',
    '@': ' @ ',
    '"': ' " ',
    '(': ' ( ',
    ')': ' ) ',
    '[': ' [ ',
    ']': ' ] ',
    ':': ' : ',
    ';': ' ; ',
    ',': ' , ',
    "'": " ' ",
}

pattern_dict = {
    r"(_+)": "_",
    r"\d+st": " st",
    r"\d+nd": " nd",
    r"\d+rd": " rd",
    r"\d+th": " th",
    r"\d+s": " s",
    r"\d+mph": " mph",
    r"\d+pm": " pm",
    r"\d+kg": " kg",
    r"\d+km": " km",
    r"\d+p": " p",
    r"\d+era": " era",
    r"s(o+)": "so",
    r"ug(h+)": "ugh",
    r"a+gh": "agh",
    r"(a+)(h+)": "ah",
    r"(u+)(h+)": "uh",
    r"(h+)(m+)": "hm",
    r"hu(m+)": "hum",
    r"m(m+)": "mm",
    r"(o+)(h+)": "oh",
    r"u(m+)": "um",
    r"b(r+)": "brr",
    r"disturbe": "disturbed",
    r"cant": " can not",
    r"forme": 'for me',
    r"judg": 'judge',
    r"clini": 'clinic',
    r"fide": 'ride',
    r"somet": "some",
    r"machin": "machine",
    r"augh": "ugh",
    r"beens": "beans",
    r"lous": "louis",
    r"inhis": "in his",
    r"wock": "work",
    r"victori": "victoria",
    r"interviewe": 'interviewee',
    r"evenin": 'evening',
}

spelling_dict = {
    "restau-rant": "restaurant",
    "joes": "does",
    "theatcr": "theater",
    "volumn": "volume",
    "meanns": "means",
    "speakes": "speakers",
    "professer": "professor",
    "franch": "french",
    "nosiy": "noisy",
    "mter":"before",
    "woinan": "woman",
    "accout": "account",
    "companuy": "company",
    "jetta": "jatta",
    "plice": "price",
    "moring": "morning",
    "aero-planes": "airplanes",
    "germen": "german",
    "dissert": "dessert",
    'octorber': 'october',
    "cornor": "corner",
    "ouhhhh": "ouch",
    "gsry": "gary",
    'boen': 'been',
    "prefes": "prefers",
    "weman": "woman",
    'cohunn': 'column',
    'yeap': 'yeah',
    'alrigh ': 'alright ',
    'infered': 'inferred',
    'idition': 'edition',
    "inspaire": "inspire",
    'consulant': 'consultant',
    "bithday": "birthday",
    "yound": "young",
    "sceond": "second",
    "extremly": "extremely",
    "jime": "jaime",
    "receiner": "receiver",
    "tallking": "talking",
    "goege": "george",
    "transfering": "transferring",
    "raido": "radio",
    "examinadons": "examinations",
    "kindergarden": "kindergarten",
    "uptairs": "upstairs",
    "transfered": "transferred",
    "headeches": "headaches",
    "acutually": "actually",
    "writting": "writing",
    "nomally": "normally",
    "phwoo": "phew",
    "embarrashed": "embarrassed",
    "picinc": "picnic",
    "knid": "kind",
    " heve": " have",
    "sustention": "suspension",
    "seience": "science",
    "wather": "water",
    "counry": "country",
    "flim": "film",
    "tallk": "talk",
    "aweful": "awful",
    "clueing": "cluing",
    "dont": "do not",
    "tenis": "tennis",
    "alway ": "always ",
    "airpotrs": "airports",
    "gardon": "garden",
    "hord": "lord",
    "wendesay": "wednesday",
    "throwed": "threw",
    "godness": "goodness",
    "aftemoon": "afternoon",
    'firday': 'friday',
    'joinning': 'joining',
    'himeself': 'himself',
    "belive": "believe",
    "runing": "running",
    "exhange": "exchange",
    "worrrisome": "worrisome",
    "coversation": "conversation",
    "intersting": "interesting",
    "yoghurt": "yogurt",
    "alawys": "always",
    "casuality": "causality",
    "begining": "beginning",
    "buttercu ": "buttercup ",
    "pr6fessor": "professor",
    "canda": "canada",
    "chicage": "chicago",
}
